uploads = []

[[generated]]
id = "dUw3bsniBgfM8MkASU9-f"
uri = "file://artifacts/bk-slides/public/hero-kitchen.png"
type = "image"
title = "generated_image"

[[generated]]
id = "kZWegDljDVXEVUa1g4wjR"
uri = "file://artifacts/bk-slides/public/grid-bg.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "Gb-bVcPmIT2FUI4uK3MIR"
uri = "file://.local/outputs/BK-Work-Schedule-Grand-Diamond.pdf"
type = "pdf"
title = "BK Work Schedule — Grand Diamond (PDF)"

[[outputs]]
id = "GPYjJ1u_F2QpI39d57CoZ"
uri = "file://.local/outputs/BK-Work-Schedule-Grand-Diamond.pptx"
type = "slides"
title = "BK Work Schedule — Grand Diamond (PPTX)"

[[outputs]]
id = "Q-Gij2szfEEuQQJzgddJj"
uri = "file://.local/outputs/CBH.pdf"
type = "pdf"
title = "CBH.pdf"
