// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/app-layout/SidebarLayout.tsx": () => import("../components/mockups/app-layout/SidebarLayout.tsx"),
  "./components/mockups/app-layout/TopNavLayout.tsx": () => import("../components/mockups/app-layout/TopNavLayout.tsx")
};
